config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/caluclator.rb
class Caluclator < ApplicationRecord
end

app/models/career.rb
class Career < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/pool.rb
class Pool < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	validates :title, presence: true, length: {minimum: 5}
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	#http_basic_authenticate_with name: "admin", password: "1q2"

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@heading = 'Страничка про нас!'
		@text = 'Привет! Меня зовут Храпунов Илья. Этот веб-сайт создан в рамках моего учебного проекта, где я изучаю разработку веб-приложений с использованием технологии Ruby on Rails. Здесь я реализовал блог, где я могу делиться своими мыслями, идеями и учебными материалами с другими студентами и людьми, интересующимися темой веб-разработки. Ruby on Rails - это мощный инструмент для быстрой и эффективной разработки веб-приложений.'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "1q2", 
		except: [:index, :show]

	def index
		@post = Post.all
	end

	def new
    	@post = Post.new
    end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])

		@post.destroy
		redirect_to posts_path
	end

	def create
		#render plain: params[:post].inspect

		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	private def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"%>
    <%= javascript_importmap_tags %>
  </head>

  <style>
   body {
    background: #ff8c00; /* Цвет фона */
    color: #80500e; /* Цвет текста */
   }
  </style>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill=#8B4513></path></svg>
        <span class="fs-4">Aviail </span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <span class="btn btn-outline-primary"><%=  link_to "Главная страница", home_path %></span>
        <span class="btn btn-outline-primary"><%=  link_to "Про нас", about_path %></span>
      </nav>
      <span class="btn btn-outline-primary"><%=  link_to "Добавление статьи", new_post_path %></span>
    </div>

    <div class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>
<p><%= @text %></p>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Название<br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		Текст статьи<br>
		<%= f.text_field(:body, {:class => 'form-control'}) %>
	</p>
	
	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<% @post.each do |post| %>
	<div class="alert alert-danger">
		<h3><%= post.title %></h3>
		<p><%= post.body %></p>
		<%= link_to "Читать далее", post_path(post), :class => 'btn btn-outline-primary' %>
	</div>
	<br>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Название<br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		Текст статьи<br>
		<%= f.text_field(:body, {:class => 'form-control'}) %>
	</p>
	
	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить пост", post_path(@post), method: :delete, data: {confirm: "Хотите удалить статью?"}, :class => 'btn btn-danger' %>
<hr>
<h2>Все комментарии</h2>
<% @post.comments.each do |comment| %>
	<div class="alert alert-light">
		<p><strong><%= comment.username %></strong>: <%= comment.body %></p>
	</div>
	<br>
<% end %>

<hr>
<h2>Добавление комментария</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		Пользователь<br>
		<%= f.text_field(:username, {:class => 'form-control'}) %>
	</p>
	<p>
		Текст комментария<br>
		<%= f.text_field(:body, {:class => 'form-control'}) %>
	</p>
	
	<p>
		<%= f.submit("Добавить комментарий", {:class => 'btn btn-warning'}) %>
	</p>
<% end %>
 